### ISSUE TITLE
create /bid API

### ISSUE THREAD

**Issue by groovecoder** [codesy/old-ruby-backend#20]
`GET /bid?url=`: If the request is authenticated, return the user's bid for that issue in JSON format:

```
{
  id: 1,
  url: "https://github.com/codesy/patronage/issues/20",
  user: "groovecoder",
  offer: 5.00,
  ask: 500.00
}
```

If the request is un-authenticated, return nothing.
Log the request somewhere (web server logs enough? database? redis? something else?) so we can start to track what issues get the most traffic.

**Comment by zerokarmaleft** [comment]
I'll namespace the api endpoints (e.g. /api/v1/bid) so that they'll be easy enough to filter from the logs.

**Comment by groovecoder** [comment]
@zerokarmaleft , @jgmize - sorry to go pre-mature optimization and everything, but in the unlikely event that hundreds of thousands of users install extensions that make these requests, will the requests still be recorded by the web server log, even if the rails/db layers go down? Is that even an intelligent question?

**Comment by zerokarmaleft** [comment]
The endpoint is namespaced under /api/v1/, so e.g. /api/v1/bids.json?url=http%3A%2F%2Fgithub.com%2Fgithubber%2Fgitproject%2Fissues%2F1
