### ISSUE TITLE
need to add CORS header to api endpoints

### ISSUE THREAD

**Issue by groovecoder** [codesy/old-ruby-backend#22]
We need to add `Access-Control-Allow-Origin: *` HTTP response header to the bids endpoint.

When I try to hit https://dev.codesy.io/bids?url=https://github.com/codesy/patronage/issues/21 from the Chrome extension, it returns:

```
XMLHttpRequest cannot load https://dev.codesy.io/bids?url=https://github.com/codesy/patronage/issues/21. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://cchpcdoagjopolebepldmfpkcbfoigok' is therefore not allowed access.
```

**Comment by zerokarmaleft** [comment]
Conditionally setting `Access-Control-Allow-Origin` to allow Origins that start with `chrome-extension://`. Otherwise it's set to `*`, though I think we should find out for sure how the extension id is generated.

**Comment by groovecoder** [comment]
Was this closed with https://github.com/codesy/patronage/commit/c2a6d5f12d797a5389e5d2b018deedaa763d8d72 ? We should start [closing issues via our commit messages](https://github.com/blog/1386-closing-issues-via-commit-messages).

**Comment by zerokarmaleft** [comment]
Yea, my bad, https://github.com/codesy/patronage/commit/c2a6d5f12d797a5389e5d2b018deedaa763d8d72 does fix this.

**Comment by groovecoder** [comment]
Hmm ... I still got the error when the Chrome extension tried to request https://codesy-dev.herokuapp.com/api/v1/bids.json?url=https://github.com/codesy/patronage/issues/22 with Origin `chrome-extension://cchpcdoagjopolebepldmfpkcbfoigok/`

![chrome_cors](https://f.cloud.github.com/assets/71928/1671173/135b40f8-5cb2-11e3-91cd-d981e45f8262.png)

When I make the request in a browser tab, the `Access-Control-Allow-Origin: *` comes back correctly:

![chrome_cors2](https://f.cloud.github.com/assets/71928/1671178/53fc6dda-5cb2-11e3-9a1f-3970237a0dcc.png)

**Comment by groovecoder** [comment]
Could it be an issue with the new `codesy-dev.herokuapp.com` server?

**Comment by groovecoder** [comment]
Nevermind, it was a manifest issue fixed in https://github.com/codesy/chrome-extension/commit/bdcd463627c11377fb318d7ce4051569c8daf450
