### ISSUE TITLE
authenticity_token during POST /bids

### ISSUE THREAD

**Issue by groovecoder** [codesy/old-ruby-backend#23]
The form to create a new bid via `POST /bids` contains an `authenticity_token` field for CSRF protection. The browser extensions don't have it, so either:
1. We create an endpoint for the browser widgets to retrieve the form itself _including_ the `authenticity_token` field value from the backend
   or
2. We disable CSRF protection on the `POST /bids` endpoint

I don't really like either option, but I lean towards 2 unless/until payments are integrated and automated in the POST.

**Comment by groovecoder** [comment]
@zerokarmaleft which of the options do you like best here? Extra thoughts on option 1:

We coule create `/api/v1/auth_token` endpoint that checks for `chrome-extension:` in the Origin and returns the CSRF token? There's still an vector for someone to create another extension to forge the request - like a CERF or something.

**Comment by jgmize** [comment]
+1 to creating a CSRF token API endpoint, but I would be more explicit and call it csrf_token -- auth_token has a very different meaning for me.

For more context, here's an example of what I think of when I read "auth_token": http://django-rest-framework.org/api-guide/authentication#tokenauthentication  -- I realize we aren't using that framework, I'm just linking the docs to illustrate the concept.

**Comment by zerokarmaleft** [comment]
@groovecoder: I'm confused on what you mean by retrieving the form on option 1 over an API endpoint.

**Comment by groovecoder** [comment]
Hmm ... yeah we don't need the whole form, just the csrf_token as @jgmize says. E.g.,

```
GET /api/v1/csrf_token

Host: api.codesy.io

Cookie: _patronage_session:ea3e662734f9c5fcf0914afd65b99fafea3e662734f9c5fcf0914afd65b99fafea3e662734f9c5fcf0914afd65b99fafea3e662734f9c5fcf0914afd65b99fafea3e662734f9c5fcf0914afd65b99faf
```

```
status: 200 OK

196c0f4352bca3ec3b6a826e7d4df3a2
```

**Comment by groovecoder** [comment]
Is this deployed to the server(s)?
